### ISSUE TITLE
Could this work with OpenJDK8?

### ISSUE THREAD

**Issue by orange451** [mojtab23/jfxgl#2]
I know this project is not maintained... But it does include a modified JFXRT on your maven. On OpenJDK8 we do not have javafx, is it possible to use this to allow for JavaFX capability?

**Comment by mojtab23** [comment]
Hi, Thank you for your attention. I think right now there are better ways to integrate high performance graphics to your javafx app.
There is an Api called [PixelBuffer](https://openjfx.io/javadoc/15/javafx.graphics/javafx/scene/image/PixelBuffer.html) that you can use.  

Take a look at this article [High Performance Rendering in JavaFX](https://foojay.io/today/high-performance-rendering-in-javafx/).
